apiVersion: rabbitmq.cloud.com/v1alpha1
kind: Rabbitmq
metadata:
  name: example-rabbitmq
spec:
  # Add fields here
  name: test # 申请不同的集群切换名字
  # 伸缩相关 bug  先缩小后在扩展会出现问题，因为设置的pv里面删除节点的数据库没有删除，所有在创建会导致启动不了，扩展和缩小需要根据负载迁移数据
  # 在一个命名空间创建两个及以上的集群为出现问题与 rabbitmq_peer_discovery_k8s 相关
  size: 3
  image: rabbitmq:3.8
  storage: 2Gi
  storageClassName: managed-nfs-storage
  serviceAccountName: rabbitmq-operator
  namespace: default
  Bash: #数组。准备列为设置ha策略
  pvLabel: # 做筛选用，可以不填
    release: rabbitmq-data
  envs:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: RABBITMQ_USE_LONGNAME
      value: "true"
    # See a note on cluster_formation.k8s.address_type in the config file section
    - name: K8S_SERVICE_NAME
      value: test # 保持和name一致，否则会产生错误
    - name: RABBITMQ_NODENAME
      value: rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local
    - name: K8S_HOSTNAME_SUFFIX
      value: .$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local
    - name: RABBITMQ_ERLANG_COOKIE
      value: "newcookie"
  data:
    enabled_plugins: |
      [rabbitmq_management,rabbitmq_peer_discovery_k8s].
    rabbitmq.conf: |
      ## Cluster formation. See https://www.rabbitmq.com/cluster-formation.html to learn more.
      cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      ## Should RabbitMQ node name be computed from the pod's hostname or IP address?
      ## IP addresses are not stable, so using [stable] hostnames is recommended when possible.
      ## Set to "hostname" to use pod hostnames.
      ## When this value is changed, so should the variable used to set the RABBITMQ_NODENAME
      ## environment variable.
      cluster_formation.k8s.address_type = hostname
      ## How often should node cleanup checks run?
      cluster_formation.node_cleanup.interval = 30
      ## Set to false if automatic removal of unknown/absent nodes
      ## is desired. This can be dangerous, see
      ##  * https://www.rabbitmq.com/cluster-formation.html#node-health-checks-and-cleanup
      ##  * https://groups.google.com/forum/#!msg/rabbitmq-users/wuOfzEywHXo/k8z_HWIkBgAJ
      cluster_formation.node_cleanup.only_log_warning = false
      cluster_partition_handling = autoheal
      ## See https://www.rabbitmq.com/ha.html#master-migration-data-locality
      queue_master_locator=min-masters
      ## This is just an example.
      ## This enables remote access for the default user with well known credentials.
      ## Consider deleting the default user and creating a separate user with a set of generated
      ## credentials instead.
      ## Learn more at https://www.rabbitmq.com/access-control.html#loopback-users
      loopback_users.guest = false
      default_pass = admin
      default_user = admin
      default_vhost = admin
# 设置账号密码与vhost，未设置会自动使用guest/guest//，此时一些权限相关的东西创建不出来，可以设置在statefulset上，但是由于设置在上面会导致出现bug（/etc/rabbitmq/xxx为只读，不允许修改）,因此设置在rabbitmq.conf上，可以尝试修改到env
